package com.checkmarx.plugin.common.sdk;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.6
 * 2016-11-20T11:18:37.656+02:00
 * Generated source version: 3.1.6
 */
@WebService(targetNamespace = "http://Checkmarx.com/v7", name = "CxSDKWebServiceSoap")
@XmlSeeAlso({ObjectFactory.class})
public interface CxSDKWebServiceSoap {

    @WebMethod(operationName = "StopDataRetention", action = "http://Checkmarx.com/v7/StopDataRetention")
    @RequestWrapper(localName = "StopDataRetention", targetNamespace = "http://Checkmarx.com/v7", className = "StopDataRetention")
    @ResponseWrapper(localName = "StopDataRetentionResponse", targetNamespace = "http://Checkmarx.com/v7", className = "StopDataRetentionResponse")
    @WebResult(name = "StopDataRetentionResult", targetNamespace = "http://Checkmarx.com/v7")
    public CxWSBasicRepsonse stopDataRetention(
            @WebParam(name = "SessionID", targetNamespace = "http://Checkmarx.com/v7")
                    String sessionID
    );

    @WebMethod(operationName = "GetTeamLdapGroupsMapping", action = "http://Checkmarx.com/v7/GetTeamLdapGroupsMapping")
    @RequestWrapper(localName = "GetTeamLdapGroupsMapping", targetNamespace = "http://Checkmarx.com/v7", className = "GetTeamLdapGroupsMapping")
    @ResponseWrapper(localName = "GetTeamLdapGroupsMappingResponse", targetNamespace = "http://Checkmarx.com/v7", className = "GetTeamLdapGroupsMappingResponse")
    @WebResult(name = "GetTeamLdapGroupsMappingResult", targetNamespace = "http://Checkmarx.com/v7")
    public CxWSResponseTeamLdapGroupMappingData getTeamLdapGroupsMapping(
            @WebParam(name = "sessionId", targetNamespace = "http://Checkmarx.com/v7")
                    String sessionId,
            @WebParam(name = "teamId", targetNamespace = "http://Checkmarx.com/v7")
                    String teamId
    );

    @WebMethod(operationName = "DeleteUser", action = "http://Checkmarx.com/v7/DeleteUser")
    @RequestWrapper(localName = "DeleteUser", targetNamespace = "http://Checkmarx.com/v7", className = "DeleteUser")
    @ResponseWrapper(localName = "DeleteUserResponse", targetNamespace = "http://Checkmarx.com/v7", className = "DeleteUserResponse")
    @WebResult(name = "DeleteUserResult", targetNamespace = "http://Checkmarx.com/v7")
    public CxWSBasicRepsonse deleteUser(
            @WebParam(name = "sessionID", targetNamespace = "http://Checkmarx.com/v7")
                    String sessionID,
            @WebParam(name = "userID", targetNamespace = "http://Checkmarx.com/v7")
                    int userID
    );

    @WebMethod(operationName = "UpdateProjectIncrementalConfiguration", action = "http://Checkmarx.com/v7/UpdateProjectIncrementalConfiguration")
    @RequestWrapper(localName = "UpdateProjectIncrementalConfiguration", targetNamespace = "http://Checkmarx.com/v7", className = "UpdateProjectIncrementalConfiguration")
    @ResponseWrapper(localName = "UpdateProjectIncrementalConfigurationResponse", targetNamespace = "http://Checkmarx.com/v7", className = "UpdateProjectIncrementalConfigurationResponse")
    @WebResult(name = "UpdateProjectIncrementalConfigurationResult", targetNamespace = "http://Checkmarx.com/v7")
    public CxWSBasicRepsonse updateProjectIncrementalConfiguration(
            @WebParam(name = "sessionID", targetNamespace = "http://Checkmarx.com/v7")
                    String sessionID,
            @WebParam(name = "projectID", targetNamespace = "http://Checkmarx.com/v7")
                    long projectID,
            @WebParam(name = "projectConfiguration", targetNamespace = "http://Checkmarx.com/v7")
                    ProjectConfiguration projectConfiguration
    );

    @WebMethod(operationName = "GetProjectsDisplayData", action = "http://Checkmarx.com/v7/GetProjectsDisplayData")
    @RequestWrapper(localName = "GetProjectsDisplayData", targetNamespace = "http://Checkmarx.com/v7", className = "GetProjectsDisplayData")
    @ResponseWrapper(localName = "GetProjectsDisplayDataResponse", targetNamespace = "http://Checkmarx.com/v7", className = "GetProjectsDisplayDataResponse")
    @WebResult(name = "GetProjectsDisplayDataResult", targetNamespace = "http://Checkmarx.com/v7")
    public CxWSResponseProjectsDisplayData getProjectsDisplayData(
            @WebParam(name = "sessionID", targetNamespace = "http://Checkmarx.com/v7")
                    String sessionID
    );

    @WebMethod(operationName = "DeleteProjects", action = "http://Checkmarx.com/v7/DeleteProjects")
    @RequestWrapper(localName = "DeleteProjects", targetNamespace = "http://Checkmarx.com/v7", className = "DeleteProjects")
    @ResponseWrapper(localName = "DeleteProjectsResponse", targetNamespace = "http://Checkmarx.com/v7", className = "DeleteProjectsResponse")
    @WebResult(name = "DeleteProjectsResult", targetNamespace = "http://Checkmarx.com/v7")
    public CxWSBasicRepsonse deleteProjects(
            @WebParam(name = "sessionID", targetNamespace = "http://Checkmarx.com/v7")
                    String sessionID,
            @WebParam(name = "projectIDs", targetNamespace = "http://Checkmarx.com/v7")
                    ArrayOfLong projectIDs
    );

    @WebMethod(operationName = "GetScanReportStatus", action = "http://Checkmarx.com/v7/GetScanReportStatus")
    @RequestWrapper(localName = "GetScanReportStatus", targetNamespace = "http://Checkmarx.com/v7", className = "GetScanReportStatus")
    @ResponseWrapper(localName = "GetScanReportStatusResponse", targetNamespace = "http://Checkmarx.com/v7", className = "GetScanReportStatusResponse")
    @WebResult(name = "GetScanReportStatusResult", targetNamespace = "http://Checkmarx.com/v7")
    public CxWSReportStatusResponse getScanReportStatus(
            @WebParam(name = "SessionID", targetNamespace = "http://Checkmarx.com/v7")
                    String sessionID,
            @WebParam(name = "ReportID", targetNamespace = "http://Checkmarx.com/v7")
                    long reportID
    );

    @WebMethod(operationName = "UpdateProjectConfiguration", action = "http://Checkmarx.com/v7/UpdateProjectConfiguration")
    @RequestWrapper(localName = "UpdateProjectConfiguration", targetNamespace = "http://Checkmarx.com/v7", className = "UpdateProjectConfiguration")
    @ResponseWrapper(localName = "UpdateProjectConfigurationResponse", targetNamespace = "http://Checkmarx.com/v7", className = "UpdateProjectConfigurationResponse")
    @WebResult(name = "UpdateProjectConfigurationResult", targetNamespace = "http://Checkmarx.com/v7")
    public CxWSBasicRepsonse updateProjectConfiguration(
            @WebParam(name = "sessionID", targetNamespace = "http://Checkmarx.com/v7")
                    String sessionID,
            @WebParam(name = "projectID", targetNamespace = "http://Checkmarx.com/v7")
                    long projectID,
            @WebParam(name = "projectConfiguration", targetNamespace = "http://Checkmarx.com/v7")
                    ProjectConfiguration projectConfiguration
    );

    @WebMethod(operationName = "ScanWithScheduling", action = "http://Checkmarx.com/v7/ScanWithScheduling")
    @RequestWrapper(localName = "ScanWithScheduling", targetNamespace = "http://Checkmarx.com/v7", className = "ScanWithScheduling")
    @ResponseWrapper(localName = "ScanWithSchedulingResponse", targetNamespace = "http://Checkmarx.com/v7", className = "ScanWithSchedulingResponse")
    @WebResult(name = "ScanWithSchedulingResult", targetNamespace = "http://Checkmarx.com/v7")
    public CxWSResponseRunID scanWithScheduling(
            @WebParam(name = "sessionId", targetNamespace = "http://Checkmarx.com/v7")
                    String sessionId,
            @WebParam(name = "args", targetNamespace = "http://Checkmarx.com/v7")
                    CliScanArgs args,
            @WebParam(name = "schedulingData", targetNamespace = "http://Checkmarx.com/v7")
                    String schedulingData
    );

    @WebMethod(operationName = "GetAllUsers", action = "http://Checkmarx.com/v7/GetAllUsers")
    @RequestWrapper(localName = "GetAllUsers", targetNamespace = "http://Checkmarx.com/v7", className = "GetAllUsers")
    @ResponseWrapper(localName = "GetAllUsersResponse", targetNamespace = "http://Checkmarx.com/v7", className = "GetAllUsersResponse")
    @WebResult(name = "GetAllUsersResult", targetNamespace = "http://Checkmarx.com/v7")
    public CxWSResponseUserData getAllUsers(
            @WebParam(name = "sessionID", targetNamespace = "http://Checkmarx.com/v7")
                    String sessionID
    );

    @WebMethod(operationName = "Logout", action = "http://Checkmarx.com/v7/Logout")
    @RequestWrapper(localName = "Logout", targetNamespace = "http://Checkmarx.com/v7", className = "Logout")
    @ResponseWrapper(localName = "LogoutResponse", targetNamespace = "http://Checkmarx.com/v7", className = "LogoutResponse")
    @WebResult(name = "LogoutResult", targetNamespace = "http://Checkmarx.com/v7")
    public CxWSBasicRepsonse logout(
            @WebParam(name = "sessionID", targetNamespace = "http://Checkmarx.com/v7")
                    String sessionID
    );

    @WebMethod(operationName = "CancelScan", action = "http://Checkmarx.com/v7/CancelScan")
    @RequestWrapper(localName = "CancelScan", targetNamespace = "http://Checkmarx.com/v7", className = "CancelScan")
    @ResponseWrapper(localName = "CancelScanResponse", targetNamespace = "http://Checkmarx.com/v7", className = "CancelScanResponse")
    @WebResult(name = "CancelScanResult", targetNamespace = "http://Checkmarx.com/v7")
    public CxWSBasicRepsonse cancelScan(
            @WebParam(name = "sessionID", targetNamespace = "http://Checkmarx.com/v7")
                    String sessionID,
            @WebParam(name = "RunId", targetNamespace = "http://Checkmarx.com/v7")
                    String runId
    );

    @WebMethod(operationName = "GetScansDisplayDataForAllProjects", action = "http://Checkmarx.com/v7/GetScansDisplayDataForAllProjects")
    @RequestWrapper(localName = "GetScansDisplayDataForAllProjects", targetNamespace = "http://Checkmarx.com/v7", className = "GetScansDisplayDataForAllProjects")
    @ResponseWrapper(localName = "GetScansDisplayDataForAllProjectsResponse", targetNamespace = "http://Checkmarx.com/v7", className = "GetScansDisplayDataForAllProjectsResponse")
    @WebResult(name = "GetScansDisplayDataForAllProjectsResult", targetNamespace = "http://Checkmarx.com/v7")
    public CxWSResponseScansDisplayData getScansDisplayDataForAllProjects(
            @WebParam(name = "sessionID", targetNamespace = "http://Checkmarx.com/v7")
                    String sessionID
    );

    @WebMethod(operationName = "DeleteScans", action = "http://Checkmarx.com/v7/DeleteScans")
    @RequestWrapper(localName = "DeleteScans", targetNamespace = "http://Checkmarx.com/v7", className = "DeleteScans")
    @ResponseWrapper(localName = "DeleteScansResponse", targetNamespace = "http://Checkmarx.com/v7", className = "DeleteScansResponse")
    @WebResult(name = "DeleteScansResult", targetNamespace = "http://Checkmarx.com/v7")
    public CxWSBasicRepsonse deleteScans(
            @WebParam(name = "sessionID", targetNamespace = "http://Checkmarx.com/v7")
                    String sessionID,
            @WebParam(name = "scanIDs", targetNamespace = "http://Checkmarx.com/v7")
                    ArrayOfLong scanIDs
    );

    @WebMethod(operationName = "GetPresetList", action = "http://Checkmarx.com/v7/GetPresetList")
    @RequestWrapper(localName = "GetPresetList", targetNamespace = "http://Checkmarx.com/v7", className = "GetPresetList")
    @ResponseWrapper(localName = "GetPresetListResponse", targetNamespace = "http://Checkmarx.com/v7", className = "GetPresetListResponse")
    @WebResult(name = "GetPresetListResult", targetNamespace = "http://Checkmarx.com/v7")
    public CxWSResponsePresetList getPresetList(
            @WebParam(name = "SessionID", targetNamespace = "http://Checkmarx.com/v7")
                    String sessionID
    );

    @WebMethod(operationName = "Login", action = "http://Checkmarx.com/v7/Login")
    @RequestWrapper(localName = "Login", targetNamespace = "http://Checkmarx.com/v7", className = "Login")
    @ResponseWrapper(localName = "LoginResponse", targetNamespace = "http://Checkmarx.com/v7", className = "LoginResponse")
    @WebResult(name = "LoginResult", targetNamespace = "http://Checkmarx.com/v7")
    public CxWSResponseLoginData login(
            @WebParam(name = "applicationCredentials", targetNamespace = "http://Checkmarx.com/v7")
                    Credentials applicationCredentials,
            @WebParam(name = "lcid", targetNamespace = "http://Checkmarx.com/v7")
                    int lcid
    );

    @WebMethod(operationName = "SetTeamLdapGroupsMapping", action = "http://Checkmarx.com/v7/SetTeamLdapGroupsMapping")
    @RequestWrapper(localName = "SetTeamLdapGroupsMapping", targetNamespace = "http://Checkmarx.com/v7", className = "SetTeamLdapGroupsMapping")
    @ResponseWrapper(localName = "SetTeamLdapGroupsMappingResponse", targetNamespace = "http://Checkmarx.com/v7", className = "SetTeamLdapGroupsMappingResponse")
    @WebResult(name = "SetTeamLdapGroupsMappingResult", targetNamespace = "http://Checkmarx.com/v7")
    public CxWSBasicRepsonse setTeamLdapGroupsMapping(
            @WebParam(name = "sessionId", targetNamespace = "http://Checkmarx.com/v7")
                    String sessionId,
            @WebParam(name = "teamId", targetNamespace = "http://Checkmarx.com/v7")
                    String teamId,
            @WebParam(name = "ldapGroups", targetNamespace = "http://Checkmarx.com/v7")
                    ArrayOfCxWSLdapGroupMapping ldapGroups
    );

    @WebMethod(operationName = "ExecuteDataRetention", action = "http://Checkmarx.com/v7/ExecuteDataRetention")
    @RequestWrapper(localName = "ExecuteDataRetention", targetNamespace = "http://Checkmarx.com/v7", className = "ExecuteDataRetention")
    @ResponseWrapper(localName = "ExecuteDataRetentionResponse", targetNamespace = "http://Checkmarx.com/v7", className = "ExecuteDataRetentionResponse")
    @WebResult(name = "ExecuteDataRetentionResult", targetNamespace = "http://Checkmarx.com/v7")
    public CxWSBasicRepsonse executeDataRetention(
            @WebParam(name = "SessionID", targetNamespace = "http://Checkmarx.com/v7")
                    String sessionID,
            @WebParam(name = "dataRetentionConfiguration", targetNamespace = "http://Checkmarx.com/v7")
                    CxDataRetentionConfiguration dataRetentionConfiguration
    );

    @WebMethod(operationName = "GetProjectScannedDisplayData", action = "http://Checkmarx.com/v7/GetProjectScannedDisplayData")
    @RequestWrapper(localName = "GetProjectScannedDisplayData", targetNamespace = "http://Checkmarx.com/v7", className = "GetProjectScannedDisplayData")
    @ResponseWrapper(localName = "GetProjectScannedDisplayDataResponse", targetNamespace = "http://Checkmarx.com/v7", className = "GetProjectScannedDisplayDataResponse")
    @WebResult(name = "GetProjectScannedDisplayDataResult", targetNamespace = "http://Checkmarx.com/v7")
    public CxWSResponseProjectScannedDisplayData getProjectScannedDisplayData(
            @WebParam(name = "sessionID", targetNamespace = "http://Checkmarx.com/v7")
                    String sessionID
    );

    @WebMethod(operationName = "GetProjectConfiguration", action = "http://Checkmarx.com/v7/GetProjectConfiguration")
    @RequestWrapper(localName = "GetProjectConfiguration", targetNamespace = "http://Checkmarx.com/v7", className = "GetProjectConfiguration")
    @ResponseWrapper(localName = "GetProjectConfigurationResponse", targetNamespace = "http://Checkmarx.com/v7", className = "GetProjectConfigurationResponse")
    @WebResult(name = "GetProjectConfigurationResult", targetNamespace = "http://Checkmarx.com/v7")
    public CxWSResponseProjectConfig getProjectConfiguration(
            @WebParam(name = "sessionID", targetNamespace = "http://Checkmarx.com/v7")
                    String sessionID,
            @WebParam(name = "projectID", targetNamespace = "http://Checkmarx.com/v7")
                    long projectID
    );

    @WebMethod(operationName = "GetAssociatedGroupsList", action = "http://Checkmarx.com/v7/GetAssociatedGroupsList")
    @RequestWrapper(localName = "GetAssociatedGroupsList", targetNamespace = "http://Checkmarx.com/v7", className = "GetAssociatedGroupsList")
    @ResponseWrapper(localName = "GetAssociatedGroupsListResponse", targetNamespace = "http://Checkmarx.com/v7", className = "GetAssociatedGroupsListResponse")
    @WebResult(name = "GetAssociatedGroupsListResult", targetNamespace = "http://Checkmarx.com/v7")
    public CxWSResponseGroupList getAssociatedGroupsList(
            @WebParam(name = "SessionID", targetNamespace = "http://Checkmarx.com/v7")
                    String sessionID
    );

    @WebMethod(operationName = "GetStatusOfSingleScan", action = "http://Checkmarx.com/v7/GetStatusOfSingleScan")
    @RequestWrapper(localName = "GetStatusOfSingleScan", targetNamespace = "http://Checkmarx.com/v7", className = "GetStatusOfSingleScan")
    @ResponseWrapper(localName = "GetStatusOfSingleScanResponse", targetNamespace = "http://Checkmarx.com/v7", className = "GetStatusOfSingleScanResponse")
    @WebResult(name = "GetStatusOfSingleScanResult", targetNamespace = "http://Checkmarx.com/v7")
    public CxWSResponseScanStatus getStatusOfSingleScan(
            @WebParam(name = "sessionID", targetNamespace = "http://Checkmarx.com/v7")
                    String sessionID,
            @WebParam(name = "runId", targetNamespace = "http://Checkmarx.com/v7")
                    String runId
    );

    @WebMethod(operationName = "GetScanReport", action = "http://Checkmarx.com/v7/GetScanReport")
    @RequestWrapper(localName = "GetScanReport", targetNamespace = "http://Checkmarx.com/v7", className = "GetScanReport")
    @ResponseWrapper(localName = "GetScanReportResponse", targetNamespace = "http://Checkmarx.com/v7", className = "GetScanReportResponse")
    @WebResult(name = "GetScanReportResult", targetNamespace = "http://Checkmarx.com/v7")
    public CxWSResponseScanResults getScanReport(
            @WebParam(name = "SessionID", targetNamespace = "http://Checkmarx.com/v7")
                    String sessionID,
            @WebParam(name = "ReportID", targetNamespace = "http://Checkmarx.com/v7")
                    long reportID
    );

    @WebMethod(operationName = "GetConfigurationSetList", action = "http://Checkmarx.com/v7/GetConfigurationSetList")
    @RequestWrapper(localName = "GetConfigurationSetList", targetNamespace = "http://Checkmarx.com/v7", className = "GetConfigurationSetList")
    @ResponseWrapper(localName = "GetConfigurationSetListResponse", targetNamespace = "http://Checkmarx.com/v7", className = "GetConfigurationSetListResponse")
    @WebResult(name = "GetConfigurationSetListResult", targetNamespace = "http://Checkmarx.com/v7")
    public CxWSResponseConfigSetList getConfigurationSetList(
            @WebParam(name = "SessionID", targetNamespace = "http://Checkmarx.com/v7")
                    String sessionID
    );

    @WebMethod(operationName = "UpdateScanComment", action = "http://Checkmarx.com/v7/UpdateScanComment")
    @RequestWrapper(localName = "UpdateScanComment", targetNamespace = "http://Checkmarx.com/v7", className = "UpdateScanComment")
    @ResponseWrapper(localName = "UpdateScanCommentResponse", targetNamespace = "http://Checkmarx.com/v7", className = "UpdateScanCommentResponse")
    @WebResult(name = "UpdateScanCommentResult", targetNamespace = "http://Checkmarx.com/v7")
    public CxWSBasicRepsonse updateScanComment(
            @WebParam(name = "sessionID", targetNamespace = "http://Checkmarx.com/v7")
                    String sessionID,
            @WebParam(name = "ScanID", targetNamespace = "http://Checkmarx.com/v7")
                    long scanID,
            @WebParam(name = "Comment", targetNamespace = "http://Checkmarx.com/v7")
                    String comment
    );

    @WebMethod(operationName = "GetScanSummary", action = "http://Checkmarx.com/v7/GetScanSummary")
    @RequestWrapper(localName = "GetScanSummary", targetNamespace = "http://Checkmarx.com/v7", className = "GetScanSummary")
    @ResponseWrapper(localName = "GetScanSummaryResponse", targetNamespace = "http://Checkmarx.com/v7", className = "GetScanSummaryResponse")
    @WebResult(name = "GetScanSummaryResult", targetNamespace = "http://Checkmarx.com/v7")
    public CxWSResponseScanSummary getScanSummary(
            @WebParam(name = "SessionID", targetNamespace = "http://Checkmarx.com/v7")
                    String sessionID,
            @WebParam(name = "ScanID", targetNamespace = "http://Checkmarx.com/v7")
                    long scanID
    );

    @WebMethod(operationName = "ScanWithOriginName", action = "http://Checkmarx.com/v7/ScanWithOriginName")
    @RequestWrapper(localName = "ScanWithOriginName", targetNamespace = "http://Checkmarx.com/v7", className = "ScanWithOriginName")
    @ResponseWrapper(localName = "ScanWithOriginNameResponse", targetNamespace = "http://Checkmarx.com/v7", className = "ScanWithOriginNameResponse")
    @WebResult(name = "ScanWithOriginNameResult", targetNamespace = "http://Checkmarx.com/v7")
    public CxWSResponseRunID scanWithOriginName(
            @WebParam(name = "sessionId", targetNamespace = "http://Checkmarx.com/v7")
                    String sessionId,
            @WebParam(name = "args", targetNamespace = "http://Checkmarx.com/v7")
                    CliScanArgs args,
            @WebParam(name = "origName", targetNamespace = "http://Checkmarx.com/v7")
                    String origName
    );

    @WebMethod(operationName = "Scan", action = "http://Checkmarx.com/v7/Scan")
    @RequestWrapper(localName = "Scan", targetNamespace = "http://Checkmarx.com/v7", className = "Scan")
    @ResponseWrapper(localName = "ScanResponse", targetNamespace = "http://Checkmarx.com/v7", className = "ScanResponse")
    @WebResult(name = "ScanResult", targetNamespace = "http://Checkmarx.com/v7")
    public CxWSResponseRunID scan(
            @WebParam(name = "sessionId", targetNamespace = "http://Checkmarx.com/v7")
                    String sessionId,
            @WebParam(name = "args", targetNamespace = "http://Checkmarx.com/v7")
                    CliScanArgs args
    );

    @WebMethod(operationName = "ScanWithSchedulingWithCron", action = "http://Checkmarx.com/v7/ScanWithSchedulingWithCron")
    @RequestWrapper(localName = "ScanWithSchedulingWithCron", targetNamespace = "http://Checkmarx.com/v7", className = "ScanWithSchedulingWithCron")
    @ResponseWrapper(localName = "ScanWithSchedulingWithCronResponse", targetNamespace = "http://Checkmarx.com/v7", className = "ScanWithSchedulingWithCronResponse")
    @WebResult(name = "ScanWithSchedulingWithCronResult", targetNamespace = "http://Checkmarx.com/v7")
    public CxWSResponseRunID scanWithSchedulingWithCron(
            @WebParam(name = "sessionId", targetNamespace = "http://Checkmarx.com/v7")
                    String sessionId,
            @WebParam(name = "args", targetNamespace = "http://Checkmarx.com/v7")
                    CliScanArgs args,
            @WebParam(name = "cronString", targetNamespace = "http://Checkmarx.com/v7")
                    String cronString,
            @WebParam(name = "utcEpochStartTime", targetNamespace = "http://Checkmarx.com/v7")
                    long utcEpochStartTime,
            @WebParam(name = "utcEpochEndTime", targetNamespace = "http://Checkmarx.com/v7")
                    long utcEpochEndTime
    );

    @WebMethod(operationName = "CreateScanReport", action = "http://Checkmarx.com/v7/CreateScanReport")
    @RequestWrapper(localName = "CreateScanReport", targetNamespace = "http://Checkmarx.com/v7", className = "CreateScanReport")
    @ResponseWrapper(localName = "CreateScanReportResponse", targetNamespace = "http://Checkmarx.com/v7", className = "CreateScanReportResponse")
    @WebResult(name = "CreateScanReportResult", targetNamespace = "http://Checkmarx.com/v7")
    public CxWSCreateReportResponse createScanReport(
            @WebParam(name = "sessionID", targetNamespace = "http://Checkmarx.com/v7")
                    String sessionID,
            @WebParam(name = "reportRequest", targetNamespace = "http://Checkmarx.com/v7")
                    CxWSReportRequest reportRequest
    );

    @WebMethod(operationName = "LoginWithToken", action = "http://Checkmarx.com/v7/LoginWithToken")
    @RequestWrapper(localName = "LoginWithToken", targetNamespace = "http://Checkmarx.com/v7", className = "LoginWithToken")
    @ResponseWrapper(localName = "LoginWithTokenResponse", targetNamespace = "http://Checkmarx.com/v7", className = "LoginWithTokenResponse")
    @WebResult(name = "LoginWithTokenResult", targetNamespace = "http://Checkmarx.com/v7")
    public CxWSResponseLoginData loginWithToken(
            @WebParam(name = "token", targetNamespace = "http://Checkmarx.com/v7")
                    String token,
            @WebParam(name = "lcid", targetNamespace = "http://Checkmarx.com/v7")
                    int lcid
    );
}
