package com.cx.plugin.common.sdk;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import javax.xml.namespace.QName;
import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;

/**
 * This class was generated by Apache CXF 3.1.6
 * 2016-11-20T11:18:37.639+02:00
 * Generated source version: 3.1.6
 */
public final class CxSDKWebServiceSoap_CxSDKWebServiceSoap_Client {

    private static final QName SERVICE_NAME = new QName("http://Checkmarx.com/v7", "CxSDKWebService");

    private CxSDKWebServiceSoap_CxSDKWebServiceSoap_Client() {
    }

    public static void main(String args[]) throws Exception {
        URL wsdlURL = CxSDKWebService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }

        CxSDKWebService ss = new CxSDKWebService(wsdlURL, SERVICE_NAME);
        CxSDKWebServiceSoap port = ss.getCxSDKWebServiceSoap();

        {
            System.out.println("Invoking stopDataRetention...");
            String _stopDataRetention_sessionID = "";
            com.cx.plugin.common.sdk.CxWSBasicRepsonse _stopDataRetention__return = port.stopDataRetention(_stopDataRetention_sessionID);
            System.out.println("stopDataRetention.result=" + _stopDataRetention__return);


        }
        {
            System.out.println("Invoking getTeamLdapGroupsMapping...");
            String _getTeamLdapGroupsMapping_sessionId = "";
            String _getTeamLdapGroupsMapping_teamId = "";
            com.cx.plugin.common.sdk.CxWSResponseTeamLdapGroupMappingData _getTeamLdapGroupsMapping__return = port.getTeamLdapGroupsMapping(_getTeamLdapGroupsMapping_sessionId, _getTeamLdapGroupsMapping_teamId);
            System.out.println("getTeamLdapGroupsMapping.result=" + _getTeamLdapGroupsMapping__return);


        }
        {
            System.out.println("Invoking deleteUser...");
            String _deleteUser_sessionID = "";
            int _deleteUser_userID = 0;
            com.cx.plugin.common.sdk.CxWSBasicRepsonse _deleteUser__return = port.deleteUser(_deleteUser_sessionID, _deleteUser_userID);
            System.out.println("deleteUser.result=" + _deleteUser__return);


        }
        {
            System.out.println("Invoking updateProjectIncrementalConfiguration...");
            String _updateProjectIncrementalConfiguration_sessionID = "";
            long _updateProjectIncrementalConfiguration_projectID = 0;
            com.cx.plugin.common.sdk.ProjectConfiguration _updateProjectIncrementalConfiguration_projectConfiguration = null;
            com.cx.plugin.common.sdk.CxWSBasicRepsonse _updateProjectIncrementalConfiguration__return = port.updateProjectIncrementalConfiguration(_updateProjectIncrementalConfiguration_sessionID, _updateProjectIncrementalConfiguration_projectID, _updateProjectIncrementalConfiguration_projectConfiguration);
            System.out.println("updateProjectIncrementalConfiguration.result=" + _updateProjectIncrementalConfiguration__return);


        }
        {
            System.out.println("Invoking getProjectsDisplayData...");
            String _getProjectsDisplayData_sessionID = "";
            com.cx.plugin.common.sdk.CxWSResponseProjectsDisplayData _getProjectsDisplayData__return = port.getProjectsDisplayData(_getProjectsDisplayData_sessionID);
            System.out.println("getProjectsDisplayData.result=" + _getProjectsDisplayData__return);


        }
        {
            System.out.println("Invoking deleteProjects...");
            String _deleteProjects_sessionID = "";
            com.cx.plugin.common.sdk.ArrayOfLong _deleteProjects_projectIDs = null;
            com.cx.plugin.common.sdk.CxWSBasicRepsonse _deleteProjects__return = port.deleteProjects(_deleteProjects_sessionID, _deleteProjects_projectIDs);
            System.out.println("deleteProjects.result=" + _deleteProjects__return);


        }
        {
            System.out.println("Invoking getScanReportStatus...");
            String _getScanReportStatus_sessionID = "";
            long _getScanReportStatus_reportID = 0;
            com.cx.plugin.common.sdk.CxWSReportStatusResponse _getScanReportStatus__return = port.getScanReportStatus(_getScanReportStatus_sessionID, _getScanReportStatus_reportID);
            System.out.println("getScanReportStatus.result=" + _getScanReportStatus__return);


        }
        {
            System.out.println("Invoking updateProjectConfiguration...");
            String _updateProjectConfiguration_sessionID = "";
            long _updateProjectConfiguration_projectID = 0;
            com.cx.plugin.common.sdk.ProjectConfiguration _updateProjectConfiguration_projectConfiguration = null;
            com.cx.plugin.common.sdk.CxWSBasicRepsonse _updateProjectConfiguration__return = port.updateProjectConfiguration(_updateProjectConfiguration_sessionID, _updateProjectConfiguration_projectID, _updateProjectConfiguration_projectConfiguration);
            System.out.println("updateProjectConfiguration.result=" + _updateProjectConfiguration__return);


        }
        {
            System.out.println("Invoking scanWithScheduling...");
            String _scanWithScheduling_sessionId = "";
            com.cx.plugin.common.sdk.CliScanArgs _scanWithScheduling_args = null;
            String _scanWithScheduling_schedulingData = "";
            com.cx.plugin.common.sdk.CxWSResponseRunID _scanWithScheduling__return = port.scanWithScheduling(_scanWithScheduling_sessionId, _scanWithScheduling_args, _scanWithScheduling_schedulingData);
            System.out.println("scanWithScheduling.result=" + _scanWithScheduling__return);


        }
        {
            System.out.println("Invoking getAllUsers...");
            String _getAllUsers_sessionID = "";
            com.cx.plugin.common.sdk.CxWSResponseUserData _getAllUsers__return = port.getAllUsers(_getAllUsers_sessionID);
            System.out.println("getAllUsers.result=" + _getAllUsers__return);


        }
        {
            System.out.println("Invoking logout...");
            String _logout_sessionID = "";
            com.cx.plugin.common.sdk.CxWSBasicRepsonse _logout__return = port.logout(_logout_sessionID);
            System.out.println("logout.result=" + _logout__return);


        }
        {
            System.out.println("Invoking cancelScan...");
            String _cancelScan_sessionID = "";
            String _cancelScan_runId = "";
            com.cx.plugin.common.sdk.CxWSBasicRepsonse _cancelScan__return = port.cancelScan(_cancelScan_sessionID, _cancelScan_runId);
            System.out.println("cancelScan.result=" + _cancelScan__return);


        }
        {
            System.out.println("Invoking getScansDisplayDataForAllProjects...");
            String _getScansDisplayDataForAllProjects_sessionID = "";
            com.cx.plugin.common.sdk.CxWSResponseScansDisplayData _getScansDisplayDataForAllProjects__return = port.getScansDisplayDataForAllProjects(_getScansDisplayDataForAllProjects_sessionID);
            System.out.println("getScansDisplayDataForAllProjects.result=" + _getScansDisplayDataForAllProjects__return);


        }
        {
            System.out.println("Invoking deleteScans...");
            String _deleteScans_sessionID = "";
            com.cx.plugin.common.sdk.ArrayOfLong _deleteScans_scanIDs = null;
            com.cx.plugin.common.sdk.CxWSBasicRepsonse _deleteScans__return = port.deleteScans(_deleteScans_sessionID, _deleteScans_scanIDs);
            System.out.println("deleteScans.result=" + _deleteScans__return);


        }
        {
            System.out.println("Invoking getPresetList...");
            String _getPresetList_sessionID = "";
            com.cx.plugin.common.sdk.CxWSResponsePresetList _getPresetList__return = port.getPresetList(_getPresetList_sessionID);
            System.out.println("getPresetList.result=" + _getPresetList__return);


        }
        {
            System.out.println("Invoking login...");
            com.cx.plugin.common.sdk.Credentials _login_applicationCredentials = null;
            int _login_lcid = 0;
            com.cx.plugin.common.sdk.CxWSResponseLoginData _login__return = port.login(_login_applicationCredentials, _login_lcid);
            System.out.println("login.result=" + _login__return);


        }
        {
            System.out.println("Invoking setTeamLdapGroupsMapping...");
            String _setTeamLdapGroupsMapping_sessionId = "";
            String _setTeamLdapGroupsMapping_teamId = "";
            com.cx.plugin.common.sdk.ArrayOfCxWSLdapGroupMapping _setTeamLdapGroupsMapping_ldapGroups = null;
            com.cx.plugin.common.sdk.CxWSBasicRepsonse _setTeamLdapGroupsMapping__return = port.setTeamLdapGroupsMapping(_setTeamLdapGroupsMapping_sessionId, _setTeamLdapGroupsMapping_teamId, _setTeamLdapGroupsMapping_ldapGroups);
            System.out.println("setTeamLdapGroupsMapping.result=" + _setTeamLdapGroupsMapping__return);


        }
        {
            System.out.println("Invoking executeDataRetention...");
            String _executeDataRetention_sessionID = "";
            com.cx.plugin.common.sdk.CxDataRetentionConfiguration _executeDataRetention_dataRetentionConfiguration = null;
            com.cx.plugin.common.sdk.CxWSBasicRepsonse _executeDataRetention__return = port.executeDataRetention(_executeDataRetention_sessionID, _executeDataRetention_dataRetentionConfiguration);
            System.out.println("executeDataRetention.result=" + _executeDataRetention__return);


        }
        {
            System.out.println("Invoking getProjectScannedDisplayData...");
            String _getProjectScannedDisplayData_sessionID = "";
            com.cx.plugin.common.sdk.CxWSResponseProjectScannedDisplayData _getProjectScannedDisplayData__return = port.getProjectScannedDisplayData(_getProjectScannedDisplayData_sessionID);
            System.out.println("getProjectScannedDisplayData.result=" + _getProjectScannedDisplayData__return);


        }
        {
            System.out.println("Invoking getProjectConfiguration...");
            String _getProjectConfiguration_sessionID = "";
            long _getProjectConfiguration_projectID = 0;
            com.cx.plugin.common.sdk.CxWSResponseProjectConfig _getProjectConfiguration__return = port.getProjectConfiguration(_getProjectConfiguration_sessionID, _getProjectConfiguration_projectID);
            System.out.println("getProjectConfiguration.result=" + _getProjectConfiguration__return);


        }
        {
            System.out.println("Invoking getAssociatedGroupsList...");
            String _getAssociatedGroupsList_sessionID = "";
            com.cx.plugin.common.sdk.CxWSResponseGroupList _getAssociatedGroupsList__return = port.getAssociatedGroupsList(_getAssociatedGroupsList_sessionID);
            System.out.println("getAssociatedGroupsList.result=" + _getAssociatedGroupsList__return);


        }
        {
            System.out.println("Invoking getStatusOfSingleScan...");
            String _getStatusOfSingleScan_sessionID = "";
            String _getStatusOfSingleScan_runId = "";
            com.cx.plugin.common.sdk.CxWSResponseScanStatus _getStatusOfSingleScan__return = port.getStatusOfSingleScan(_getStatusOfSingleScan_sessionID, _getStatusOfSingleScan_runId);
            System.out.println("getStatusOfSingleScan.result=" + _getStatusOfSingleScan__return);


        }
        {
            System.out.println("Invoking getScanReport...");
            String _getScanReport_sessionID = "";
            long _getScanReport_reportID = 0;
            com.cx.plugin.common.sdk.CxWSResponseScanResults _getScanReport__return = port.getScanReport(_getScanReport_sessionID, _getScanReport_reportID);
            System.out.println("getScanReport.result=" + _getScanReport__return);


        }
        {
            System.out.println("Invoking getConfigurationSetList...");
            String _getConfigurationSetList_sessionID = "";
            com.cx.plugin.common.sdk.CxWSResponseConfigSetList _getConfigurationSetList__return = port.getConfigurationSetList(_getConfigurationSetList_sessionID);
            System.out.println("getConfigurationSetList.result=" + _getConfigurationSetList__return);


        }
        {
            System.out.println("Invoking updateScanComment...");
            String _updateScanComment_sessionID = "";
            long _updateScanComment_scanID = 0;
            String _updateScanComment_comment = "";
            com.cx.plugin.common.sdk.CxWSBasicRepsonse _updateScanComment__return = port.updateScanComment(_updateScanComment_sessionID, _updateScanComment_scanID, _updateScanComment_comment);
            System.out.println("updateScanComment.result=" + _updateScanComment__return);


        }
        {
            System.out.println("Invoking getScanSummary...");
            String _getScanSummary_sessionID = "";
            long _getScanSummary_scanID = 0;
            com.cx.plugin.common.sdk.CxWSResponseScanSummary _getScanSummary__return = port.getScanSummary(_getScanSummary_sessionID, _getScanSummary_scanID);
            System.out.println("getScanSummary.result=" + _getScanSummary__return);


        }
        {
            System.out.println("Invoking scanWithOriginName...");
            String _scanWithOriginName_sessionId = "";
            com.cx.plugin.common.sdk.CliScanArgs _scanWithOriginName_args = null;
            String _scanWithOriginName_origName = "";
            com.cx.plugin.common.sdk.CxWSResponseRunID _scanWithOriginName__return = port.scanWithOriginName(_scanWithOriginName_sessionId, _scanWithOriginName_args, _scanWithOriginName_origName);
            System.out.println("scanWithOriginName.result=" + _scanWithOriginName__return);


        }
        {
            System.out.println("Invoking scan...");
            String _scan_sessionId = "";
            com.cx.plugin.common.sdk.CliScanArgs _scan_args = null;
            com.cx.plugin.common.sdk.CxWSResponseRunID _scan__return = port.scan(_scan_sessionId, _scan_args);
            System.out.println("scan.result=" + _scan__return);


        }
        {
            System.out.println("Invoking scanWithSchedulingWithCron...");
            String _scanWithSchedulingWithCron_sessionId = "";
            com.cx.plugin.common.sdk.CliScanArgs _scanWithSchedulingWithCron_args = null;
            String _scanWithSchedulingWithCron_cronString = "";
            long _scanWithSchedulingWithCron_utcEpochStartTime = 0;
            long _scanWithSchedulingWithCron_utcEpochEndTime = 0;
            com.cx.plugin.common.sdk.CxWSResponseRunID _scanWithSchedulingWithCron__return = port.scanWithSchedulingWithCron(_scanWithSchedulingWithCron_sessionId, _scanWithSchedulingWithCron_args, _scanWithSchedulingWithCron_cronString, _scanWithSchedulingWithCron_utcEpochStartTime, _scanWithSchedulingWithCron_utcEpochEndTime);
            System.out.println("scanWithSchedulingWithCron.result=" + _scanWithSchedulingWithCron__return);


        }
        {
            System.out.println("Invoking createScanReport...");
            String _createScanReport_sessionID = "";
            com.cx.plugin.common.sdk.CxWSReportRequest _createScanReport_reportRequest = null;
            com.cx.plugin.common.sdk.CxWSCreateReportResponse _createScanReport__return = port.createScanReport(_createScanReport_sessionID, _createScanReport_reportRequest);
            System.out.println("createScanReport.result=" + _createScanReport__return);


        }
        {
            System.out.println("Invoking loginWithToken...");
            String _loginWithToken_token = "";
            int _loginWithToken_lcid = 0;
            com.cx.plugin.common.sdk.CxWSResponseLoginData _loginWithToken__return = port.loginWithToken(_loginWithToken_token, _loginWithToken_lcid);
            System.out.println("loginWithToken.result=" + _loginWithToken__return);


        }

        System.exit(0);
    }

}
